# Generated by Django 4.1.2 on 2023-01-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profilecoach_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecoach',
            name='facebook',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilecoach',
            name='instagram',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilecoach',
            name='youtube',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
