# Generated by Django 4.1.2 on 2022-10-29 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Blog title')),
                ('date_added', models.DateField(default=datetime.date.today, verbose_name='Blog Added')),
                ('slug', models.SlugField(unique=True)),
                ('blog_text', models.TextField(verbose_name='Blog Text')),
                ('special_text', models.TextField(max_length=250, verbose_name='Special Text')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('category', models.ManyToManyField(blank=True, null=True, to='gym.blogcategory')),
            ],
        ),
    ]
