# Generated by Django 4.1.2 on 2022-11-26 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='poster',
            field=models.ImageField(null=True, upload_to='poster/', verbose_name='Poster'),
        ),
    ]
