# Generated by Django 4.1.2 on 2022-11-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_blog_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ManyToManyField(blank=True, to='gym.blogcategory'),
        ),
    ]
