# Generated by Django 4.1.2 on 2022-12-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subscription',
            field=models.BooleanField(default=False),
        ),
    ]
