# Generated by Django 4.1.2 on 2022-12-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_text_next',
            field=models.TextField(blank=True, null=True, verbose_name='Blog Text next'),
        ),
    ]
